name: release
on:
  push:
    branches: [main]

permissions:
  contents: write   # necesario para crear tags y releases

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
        - run: npm ci
        - run: npx semantic-release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}